/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.table.AbstractTableModel;
import java.util.ArrayList;
import java.time.LocalDate;
import java.util.List;
import model.Eligibility;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ASUS
 */
public class EligibilityPanel extends javax.swing.JPanel {

    /**
     * Creates new form EligibilityPanel
     */
    private List<Eligibility> eligibilityList = new ArrayList<>();

    public EligibilityPanel() {
        initComponents();
        eligibilityTable.setModel(new EligibilityTableModel(eligibilityList));
    }

    public int getEligibilityCount() {
        return eligibilityList.size();
    }

    public String getCareerService(int rowIndex) {
        return eligibilityList.get(rowIndex).getCareerService();
    }

    public String getRating(int rowIndex) {
        return eligibilityList.get(rowIndex).getRating();
    }

    public LocalDate getDateOfExamination(int rowIndex) {
        return eligibilityList.get(rowIndex).getDateOfExamination();
    }

    public String getPlaceOfExamination(int rowIndex) {
        return eligibilityList.get(rowIndex).getPlaceOfExamination();
    }

    public String getLicenseNumber(int rowIndex) {
        return eligibilityList.get(rowIndex).getLicenseNumber();
    }

    public LocalDate getLicenseDateOfValidity(int rowIndex) {
        return eligibilityList.get(rowIndex).getLicenseDateOfValidity();
    }

    private void showAddEligibilityDialog() {
        AddEligibilityDialog dialog = new AddEligibilityDialog(JOptionPane.getFrameForComponent(this), true);
        dialog.setVisible(true);
        Eligibility newEligibility = dialog.getEligibility();
        if (newEligibility != null) {
            EligibilityTableModel model = (EligibilityTableModel) eligibilityTable.getModel();
            model.addEligibility(newEligibility);
        }
    }

    private void editSelectedEligibility() {
        int selectedRow = eligibilityTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an entry to edit.", "No Entry Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Eligibility eligibilityToEdit = eligibilityList.get(selectedRow);
        AddEligibilityDialog dialog = new AddEligibilityDialog(JOptionPane.getFrameForComponent(this), true, eligibilityToEdit);
        dialog.setVisible(true);

        Eligibility updatedEligibility = dialog.getEligibility();
        if (updatedEligibility != null) {
            eligibilityList.set(selectedRow, updatedEligibility);
            ((EligibilityTableModel) eligibilityTable.getModel()).fireTableRowsUpdated(selectedRow, selectedRow);
        }
    }

    private void deleteSelectedEligibility() {
        int selectedRow = eligibilityTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an entry to delete.", "No Entry Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected entry?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            EligibilityTableModel model = (EligibilityTableModel) eligibilityTable.getModel();
            model.removeEligibility(selectedRow);
        }
    }

    public void refreshData() {
        EligibilityTableModel model = (EligibilityTableModel) eligibilityTable.getModel();
        model.clearData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        eligibilityTable = new javax.swing.JTable();
        editEligibilityBtn = new javax.swing.JButton();
        deleteEligibilityBtn = new javax.swing.JButton();
        addEligibilityBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 244, 246));

        informationLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        informationLabel.setText("Civil Service Eligibility");

        eligibilityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        eligibilityTable.setRowHeight(30);
        eligibilityTable.setShowGrid(false);
        jScrollPane1.setViewportView(eligibilityTable);

        editEligibilityBtn.setBackground(new java.awt.Color(59, 130, 246));
        editEligibilityBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        editEligibilityBtn.setForeground(new java.awt.Color(255, 255, 255));
        editEligibilityBtn.setText("Edit Eligibility");
        editEligibilityBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editEligibilityBtn.setFocusPainted(false);
        editEligibilityBtn.setMargin(new java.awt.Insets(5, 10, 5, 10));
        editEligibilityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editEligibilityBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editEligibilityBtnMouseExited(evt);
            }
        });
        editEligibilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEligibilityBtnActionPerformed(evt);
            }
        });

        deleteEligibilityBtn.setBackground(new java.awt.Color(239, 68, 68));
        deleteEligibilityBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteEligibilityBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteEligibilityBtn.setText("Delete Eligiblity");
        deleteEligibilityBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteEligibilityBtn.setFocusPainted(false);
        deleteEligibilityBtn.setMargin(new java.awt.Insets(5, 10, 5, 10));
        deleteEligibilityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteEligibilityBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteEligibilityBtnMouseExited(evt);
            }
        });
        deleteEligibilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEligibilityBtnActionPerformed(evt);
            }
        });

        addEligibilityBtn.setBackground(new java.awt.Color(16, 185, 129));
        addEligibilityBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addEligibilityBtn.setForeground(new java.awt.Color(255, 255, 255));
        addEligibilityBtn.setText("Add Eligibility");
        addEligibilityBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addEligibilityBtn.setFocusPainted(false);
        addEligibilityBtn.setMargin(new java.awt.Insets(5, 10, 5, 10));
        addEligibilityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEligibilityBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEligibilityBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addEligibilityBtnMousePressed(evt);
            }
        });
        addEligibilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEligibilityBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(informationLabel)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(addEligibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(editEligibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(deleteEligibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(informationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEligibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEligibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEligibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editEligibilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEligibilityBtnActionPerformed
        // TODO add your handling code here:
        editSelectedEligibility();

    }//GEN-LAST:event_editEligibilityBtnActionPerformed

    private void deleteEligibilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEligibilityBtnActionPerformed
        // TODO add your handling code here:
        deleteSelectedEligibility();
    }//GEN-LAST:event_deleteEligibilityBtnActionPerformed

    private void addEligibilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEligibilityBtnActionPerformed
        // TODO add your handling code here:
        showAddEligibilityDialog();
    }//GEN-LAST:event_addEligibilityBtnActionPerformed

    private void addEligibilityBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEligibilityBtnMouseEntered
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();

        button.setBackground(new Color(5, 150, 105));
    }//GEN-LAST:event_addEligibilityBtnMouseEntered

    private void addEligibilityBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEligibilityBtnMouseExited
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();

        button.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_addEligibilityBtnMouseExited

    private void addEligibilityBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEligibilityBtnMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_addEligibilityBtnMousePressed

    private void editEligibilityBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEligibilityBtnMouseEntered
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();

        button.setBackground(new Color(37, 99, 235));
    }//GEN-LAST:event_editEligibilityBtnMouseEntered

    private void editEligibilityBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEligibilityBtnMouseExited
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();

        button.setBackground(new Color(59, 130, 246));
    }//GEN-LAST:event_editEligibilityBtnMouseExited

    private void deleteEligibilityBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEligibilityBtnMouseEntered
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();

        button.setBackground(new Color(220, 38, 35));
    }//GEN-LAST:event_deleteEligibilityBtnMouseEntered

    private void deleteEligibilityBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEligibilityBtnMouseExited
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();

        button.setBackground(new Color(239, 68, 68));
    }//GEN-LAST:event_deleteEligibilityBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEligibilityBtn;
    private javax.swing.JButton deleteEligibilityBtn;
    private javax.swing.JButton editEligibilityBtn;
    private javax.swing.JTable eligibilityTable;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
