/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class FamilyBackgroundPanel extends javax.swing.JPanel {

    /**
     * Creates new form FamilyBackgroundPanel
     */
    public FamilyBackgroundPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        surnameLabel = new javax.swing.JLabel();
        spouseSurnameTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        spouseFirstNameTextField = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        spouseMiddleNameTextField = new javax.swing.JTextField();
        nameExtensionLabel = new javax.swing.JLabel();
        spouseExtTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        surnameLabel1 = new javax.swing.JLabel();
        spouseOccupationTextField = new javax.swing.JTextField();
        firstNameLabel1 = new javax.swing.JLabel();
        spouseEmployerTextField = new javax.swing.JTextField();
        middleNameLabel1 = new javax.swing.JLabel();
        bussAddressTextField = new javax.swing.JTextField();
        nameExtensionLabel1 = new javax.swing.JLabel();
        spouseTeleTextField = new javax.swing.JTextField();
        fatherSurnameTextField = new javax.swing.JTextField();
        surnameLabel2 = new javax.swing.JLabel();
        firstNameLabel2 = new javax.swing.JLabel();
        fatherFirstNameTextField = new javax.swing.JTextField();
        middleNameLabel2 = new javax.swing.JLabel();
        fatherMiddleNameTextField = new javax.swing.JTextField();
        nameExtensionLabel2 = new javax.swing.JLabel();
        fatherExtTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        motherSurnameTextField = new javax.swing.JTextField();
        surnameLabel3 = new javax.swing.JLabel();
        firstNameLabel3 = new javax.swing.JLabel();
        motherFirstNameTextField = new javax.swing.JTextField();
        middleNameLabel3 = new javax.swing.JLabel();
        motherMiddleNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(243, 244, 246));
        setPreferredSize(new java.awt.Dimension(986, 1083));

        informationLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        informationLabel.setText("Family Background");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Father Information");

        surnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel.setText("Surname");

        spouseSurnameTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseSurnameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseSurnameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseSurnameTextFieldFocusLost(evt);
            }
        });
        spouseSurnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseSurnameTextFieldActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        spouseFirstNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseFirstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseFirstNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseFirstNameTextFieldFocusLost(evt);
            }
        });
        spouseFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseFirstNameTextFieldActionPerformed(evt);
            }
        });

        middleNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameLabel.setText("Middle Name");

        spouseMiddleNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseMiddleNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseMiddleNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseMiddleNameTextFieldFocusLost(evt);
            }
        });
        spouseMiddleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseMiddleNameTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel.setText("Ext.");

        spouseExtTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseExtTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseExtTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseExtTextFieldFocusLost(evt);
            }
        });
        spouseExtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseExtTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Spouse Information");

        surnameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel1.setText("Occupation");

        spouseOccupationTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseOccupationTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseOccupationTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseOccupationTextFieldFocusLost(evt);
            }
        });
        spouseOccupationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseOccupationTextFieldActionPerformed(evt);
            }
        });

        firstNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel1.setText("Employer/Business Name");

        spouseEmployerTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseEmployerTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseEmployerTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseEmployerTextFieldFocusLost(evt);
            }
        });
        spouseEmployerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseEmployerTextFieldActionPerformed(evt);
            }
        });

        middleNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameLabel1.setText("Business Address");

        bussAddressTextField.setBackground(new java.awt.Color(250, 250, 250));
        bussAddressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bussAddressTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bussAddressTextFieldFocusLost(evt);
            }
        });
        bussAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bussAddressTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel1.setText("Telephone No.");

        spouseTeleTextField.setBackground(new java.awt.Color(250, 250, 250));
        spouseTeleTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseTeleTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseTeleTextFieldFocusLost(evt);
            }
        });
        spouseTeleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseTeleTextFieldActionPerformed(evt);
            }
        });

        fatherSurnameTextField.setBackground(new java.awt.Color(250, 250, 250));
        fatherSurnameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fatherSurnameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fatherSurnameTextFieldFocusLost(evt);
            }
        });
        fatherSurnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherSurnameTextFieldActionPerformed(evt);
            }
        });

        surnameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel2.setText("Surname");

        firstNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel2.setText("First Name");

        fatherFirstNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        fatherFirstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fatherFirstNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fatherFirstNameTextFieldFocusLost(evt);
            }
        });
        fatherFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherFirstNameTextFieldActionPerformed(evt);
            }
        });

        middleNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameLabel2.setText("Middle Name");

        fatherMiddleNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        fatherMiddleNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fatherMiddleNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fatherMiddleNameTextFieldFocusLost(evt);
            }
        });
        fatherMiddleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherMiddleNameTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel2.setText("Ext.");

        fatherExtTextField.setBackground(new java.awt.Color(250, 250, 250));
        fatherExtTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fatherExtTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fatherExtTextFieldFocusLost(evt);
            }
        });
        fatherExtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherExtTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Mother's Maiden Name");

        motherSurnameTextField.setBackground(new java.awt.Color(250, 250, 250));
        motherSurnameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motherSurnameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                motherSurnameTextFieldFocusLost(evt);
            }
        });
        motherSurnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherSurnameTextFieldActionPerformed(evt);
            }
        });

        surnameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel3.setText("Surname");

        firstNameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel3.setText("First Name");

        motherFirstNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        motherFirstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motherFirstNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                motherFirstNameTextFieldFocusLost(evt);
            }
        });
        motherFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherFirstNameTextFieldActionPerformed(evt);
            }
        });

        middleNameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameLabel3.setText("Middle Name");

        motherMiddleNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        motherMiddleNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motherMiddleNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                motherMiddleNameTextFieldFocusLost(evt);
            }
        });
        motherMiddleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherMiddleNameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Children");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(surnameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(firstNameLabel3)
                                .addGap(180, 180, 180)
                                .addComponent(middleNameLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(motherSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(motherFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(motherMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(surnameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(firstNameLabel2)
                                .addGap(180, 180, 180)
                                .addComponent(middleNameLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fatherSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(fatherFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fatherMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameExtensionLabel2)
                            .addComponent(fatherExtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(informationLabel)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(firstNameLabel)
                                        .addGap(180, 180, 180)
                                        .addComponent(middleNameLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spouseSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(spouseFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(spouseMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameExtensionLabel)
                                    .addComponent(spouseExtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spouseOccupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(spouseEmployerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(surnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(firstNameLabel1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(middleNameLabel1)
                                    .addComponent(bussAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameExtensionLabel1)
                                        .addGap(0, 120, Short.MAX_VALUE))
                                    .addComponent(spouseTeleTextField))))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2)
                    .addContainerGap(806, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(informationLabel)
                .addGap(55, 55, 55)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel)
                    .addComponent(firstNameLabel)
                    .addComponent(middleNameLabel)
                    .addComponent(nameExtensionLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spouseSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouseFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouseMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouseExtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel1)
                    .addComponent(firstNameLabel1)
                    .addComponent(middleNameLabel1)
                    .addComponent(nameExtensionLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spouseOccupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouseEmployerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bussAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouseTeleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel2)
                    .addComponent(firstNameLabel2)
                    .addComponent(middleNameLabel2)
                    .addComponent(nameExtensionLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatherSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherExtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surnameLabel3)
                    .addComponent(firstNameLabel3)
                    .addComponent(middleNameLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motherSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motherFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motherMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel2)
                    .addContainerGap(984, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spouseSurnameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseSurnameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseSurnameTextFieldFocusGained

    private void spouseSurnameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseSurnameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseSurnameTextFieldFocusLost

    private void spouseSurnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseSurnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseSurnameTextFieldActionPerformed

    private void spouseFirstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseFirstNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseFirstNameTextFieldFocusGained

    private void spouseFirstNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseFirstNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseFirstNameTextFieldFocusLost

    private void spouseFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseFirstNameTextFieldActionPerformed

    private void spouseMiddleNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseMiddleNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseMiddleNameTextFieldFocusGained

    private void spouseMiddleNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseMiddleNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseMiddleNameTextFieldFocusLost

    private void spouseMiddleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseMiddleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseMiddleNameTextFieldActionPerformed

    private void spouseExtTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseExtTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseExtTextFieldFocusGained

    private void spouseExtTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseExtTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseExtTextFieldFocusLost

    private void spouseExtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseExtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseExtTextFieldActionPerformed

    private void spouseOccupationTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseOccupationTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseOccupationTextFieldFocusGained

    private void spouseOccupationTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseOccupationTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseOccupationTextFieldFocusLost

    private void spouseOccupationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseOccupationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseOccupationTextFieldActionPerformed

    private void spouseEmployerTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseEmployerTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseEmployerTextFieldFocusGained

    private void spouseEmployerTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseEmployerTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseEmployerTextFieldFocusLost

    private void spouseEmployerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseEmployerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseEmployerTextFieldActionPerformed

    private void bussAddressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bussAddressTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bussAddressTextFieldFocusGained

    private void bussAddressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bussAddressTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bussAddressTextFieldFocusLost

    private void bussAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bussAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bussAddressTextFieldActionPerformed

    private void spouseTeleTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseTeleTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseTeleTextFieldFocusGained

    private void spouseTeleTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseTeleTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseTeleTextFieldFocusLost

    private void spouseTeleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseTeleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseTeleTextFieldActionPerformed

    private void fatherSurnameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherSurnameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherSurnameTextFieldFocusGained

    private void fatherSurnameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherSurnameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherSurnameTextFieldFocusLost

    private void fatherSurnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherSurnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherSurnameTextFieldActionPerformed

    private void fatherFirstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherFirstNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherFirstNameTextFieldFocusGained

    private void fatherFirstNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherFirstNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherFirstNameTextFieldFocusLost

    private void fatherFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherFirstNameTextFieldActionPerformed

    private void fatherMiddleNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherMiddleNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherMiddleNameTextFieldFocusGained

    private void fatherMiddleNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherMiddleNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherMiddleNameTextFieldFocusLost

    private void fatherMiddleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherMiddleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherMiddleNameTextFieldActionPerformed

    private void fatherExtTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherExtTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherExtTextFieldFocusGained

    private void fatherExtTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherExtTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherExtTextFieldFocusLost

    private void fatherExtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherExtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherExtTextFieldActionPerformed

    private void motherSurnameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherSurnameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_motherSurnameTextFieldFocusGained

    private void motherSurnameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherSurnameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_motherSurnameTextFieldFocusLost

    private void motherSurnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherSurnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherSurnameTextFieldActionPerformed

    private void motherFirstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherFirstNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_motherFirstNameTextFieldFocusGained

    private void motherFirstNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherFirstNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_motherFirstNameTextFieldFocusLost

    private void motherFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherFirstNameTextFieldActionPerformed

    private void motherMiddleNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherMiddleNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_motherMiddleNameTextFieldFocusGained

    private void motherMiddleNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherMiddleNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_motherMiddleNameTextFieldFocusLost

    private void motherMiddleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherMiddleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherMiddleNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bussAddressTextField;
    private javax.swing.JTextField fatherExtTextField;
    private javax.swing.JTextField fatherFirstNameTextField;
    private javax.swing.JTextField fatherMiddleNameTextField;
    private javax.swing.JTextField fatherSurnameTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel firstNameLabel3;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JLabel middleNameLabel1;
    private javax.swing.JLabel middleNameLabel2;
    private javax.swing.JLabel middleNameLabel3;
    private javax.swing.JTextField motherFirstNameTextField;
    private javax.swing.JTextField motherMiddleNameTextField;
    private javax.swing.JTextField motherSurnameTextField;
    private javax.swing.JLabel nameExtensionLabel;
    private javax.swing.JLabel nameExtensionLabel1;
    private javax.swing.JLabel nameExtensionLabel2;
    private javax.swing.JTextField spouseEmployerTextField;
    private javax.swing.JTextField spouseExtTextField;
    private javax.swing.JTextField spouseFirstNameTextField;
    private javax.swing.JTextField spouseMiddleNameTextField;
    private javax.swing.JTextField spouseOccupationTextField;
    private javax.swing.JTextField spouseSurnameTextField;
    private javax.swing.JTextField spouseTeleTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel surnameLabel1;
    private javax.swing.JLabel surnameLabel2;
    private javax.swing.JLabel surnameLabel3;
    // End of variables declaration//GEN-END:variables
}
