/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author ASUS
 */
public class PersonalInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalInfoPanel
     */
    public PersonalInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexButtonGroup = new javax.swing.ButtonGroup();
        civilStatusButtonGroup = new javax.swing.ButtonGroup();
        citizenshipButtonGroup = new javax.swing.ButtonGroup();
        citizenshipGroup = new javax.swing.ButtonGroup();
        informationLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        placeOfBirthTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        nameExtensionTextField = new javax.swing.JTextField();
        nameExtensionLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        surnameLabel1 = new javax.swing.JLabel();
        femaleButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        singleButton = new javax.swing.JRadioButton();
        marriedButton = new javax.swing.JRadioButton();
        widowedButton = new javax.swing.JRadioButton();
        separateButton = new javax.swing.JRadioButton();
        otherButton = new javax.swing.JRadioButton();
        dobLabel = new javax.swing.JLabel();
        dateOfBirthTextField = new javax.swing.JFormattedTextField();
        dobLabel1 = new javax.swing.JLabel();
        firstNameTextField1 = new javax.swing.JTextField();
        placeOfBirthTextField1 = new javax.swing.JTextField();
        dobLabel2 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        nameExtensionLabel1 = new javax.swing.JLabel();
        bloodTypeTextField = new javax.swing.JTextField();
        nameExtensionLabel2 = new javax.swing.JLabel();
        gsisIdNoTextField = new javax.swing.JTextField();
        nameExtensionLabel3 = new javax.swing.JLabel();
        pagIbigIdNoTextField = new javax.swing.JTextField();
        nameExtensionLabel4 = new javax.swing.JLabel();
        philHealthNo = new javax.swing.JTextField();
        nameExtensionLabel5 = new javax.swing.JLabel();
        sssNoTextField = new javax.swing.JTextField();
        nameExtensionLabel6 = new javax.swing.JLabel();
        tinNoTextField = new javax.swing.JTextField();
        nameExtensionLabel7 = new javax.swing.JLabel();
        agencyEmployeeNoTextField = new javax.swing.JTextField();
        nameExtensionLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        filipinoButton = new javax.swing.JRadioButton();
        surnameLabel2 = new javax.swing.JLabel();
        dualCitizenshipButton = new javax.swing.JRadioButton();
        citizenshipByNaturalizationRadioButton = new javax.swing.JRadioButton();
        citizenshipByBirthRadioButton = new javax.swing.JRadioButton();
        surnameLabel3 = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");

        informationLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        informationLabel.setText("Personal Information");

        surnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel.setText("Surname");

        surnameTextField.setBackground(new java.awt.Color(250, 250, 250));
        surnameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                surnameTextFieldFocusLost(evt);
            }
        });
        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });

        placeOfBirthTextField.setBackground(new java.awt.Color(250, 250, 250));
        placeOfBirthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                placeOfBirthTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                placeOfBirthTextFieldFocusLost(evt);
            }
        });
        placeOfBirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOfBirthTextFieldActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        middleNameTextField.setBackground(new java.awt.Color(250, 250, 250));
        middleNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middleNameTextFieldFocusLost(evt);
            }
        });
        middleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTextFieldActionPerformed(evt);
            }
        });

        middleNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameLabel.setText("Middle Name");

        nameExtensionTextField.setBackground(new java.awt.Color(250, 250, 250));
        nameExtensionTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameExtensionTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameExtensionTextFieldFocusLost(evt);
            }
        });
        nameExtensionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameExtensionTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel.setText("Name Extension (JR., SR.)");

        sexButtonGroup.add(maleButton);
        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        surnameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel1.setText("Sex");

        sexButtonGroup.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Civil Status");

        civilStatusButtonGroup.add(singleButton);
        singleButton.setText("Single");
        singleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleButtonActionPerformed(evt);
            }
        });

        civilStatusButtonGroup.add(marriedButton);
        marriedButton.setText("Married");
        marriedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marriedButtonActionPerformed(evt);
            }
        });

        civilStatusButtonGroup.add(widowedButton);
        widowedButton.setText("Widowed");
        widowedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widowedButtonActionPerformed(evt);
            }
        });

        civilStatusButtonGroup.add(separateButton);
        separateButton.setText("Separate");
        separateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                separateButtonActionPerformed(evt);
            }
        });

        civilStatusButtonGroup.add(otherButton);
        otherButton.setText("Other/s");
        otherButton.setToolTipText("");
        otherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherButtonActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobLabel.setText("Date of Birth (mm/dd/yy)");
        dobLabel.setToolTipText("");

        dateOfBirthTextField.setBackground(new java.awt.Color(250, 250, 250));
        dateOfBirthTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));

        dobLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobLabel1.setText("Place of Birth");
        dobLabel1.setToolTipText("");

        firstNameTextField1.setBackground(new java.awt.Color(250, 250, 250));
        firstNameTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameTextField1FocusLost(evt);
            }
        });
        firstNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextField1ActionPerformed(evt);
            }
        });

        placeOfBirthTextField1.setBackground(new java.awt.Color(250, 250, 250));
        placeOfBirthTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                placeOfBirthTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                placeOfBirthTextField1FocusLost(evt);
            }
        });
        placeOfBirthTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOfBirthTextField1ActionPerformed(evt);
            }
        });

        dobLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobLabel2.setText("Height (m)");
        dobLabel2.setToolTipText("");

        weightTextField.setBackground(new java.awt.Color(250, 250, 250));
        weightTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weightTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                weightTextFieldFocusLost(evt);
            }
        });
        weightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel1.setText("Weight (kg)");

        bloodTypeTextField.setBackground(new java.awt.Color(250, 250, 250));
        bloodTypeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bloodTypeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bloodTypeTextFieldFocusLost(evt);
            }
        });
        bloodTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypeTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel2.setText("Blood Type");

        gsisIdNoTextField.setBackground(new java.awt.Color(250, 250, 250));
        gsisIdNoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gsisIdNoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gsisIdNoTextFieldFocusLost(evt);
            }
        });
        gsisIdNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsisIdNoTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel3.setText("GSIS ID No.");

        pagIbigIdNoTextField.setBackground(new java.awt.Color(250, 250, 250));
        pagIbigIdNoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pagIbigIdNoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pagIbigIdNoTextFieldFocusLost(evt);
            }
        });
        pagIbigIdNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagIbigIdNoTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel4.setText("PAG-IBIG ID No.");

        philHealthNo.setBackground(new java.awt.Color(250, 250, 250));
        philHealthNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                philHealthNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                philHealthNoFocusLost(evt);
            }
        });
        philHealthNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philHealthNoActionPerformed(evt);
            }
        });

        nameExtensionLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel5.setText("PhilHealth No.");

        sssNoTextField.setBackground(new java.awt.Color(250, 250, 250));
        sssNoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sssNoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sssNoTextFieldFocusLost(evt);
            }
        });
        sssNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssNoTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel6.setText("SSS No.");

        tinNoTextField.setBackground(new java.awt.Color(250, 250, 250));
        tinNoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tinNoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tinNoTextFieldFocusLost(evt);
            }
        });
        tinNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinNoTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel7.setText("TIN No.");

        agencyEmployeeNoTextField.setBackground(new java.awt.Color(250, 250, 250));
        agencyEmployeeNoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                agencyEmployeeNoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                agencyEmployeeNoTextFieldFocusLost(evt);
            }
        });
        agencyEmployeeNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agencyEmployeeNoTextFieldActionPerformed(evt);
            }
        });

        nameExtensionLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameExtensionLabel8.setText("Agency Employee No.");

        citizenshipButtonGroup.add(filipinoButton);
        filipinoButton.setText("Filipino");
        filipinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filipinoButtonActionPerformed(evt);
            }
        });

        surnameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel2.setText("Citizenship");

        citizenshipButtonGroup.add(dualCitizenshipButton);
        dualCitizenshipButton.setText("Dual Citizenship");
        dualCitizenshipButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dualCitizenshipButtonItemStateChanged(evt);
            }
        });
        dualCitizenshipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dualCitizenshipButtonActionPerformed(evt);
            }
        });

        citizenshipGroup.add(citizenshipByNaturalizationRadioButton);
        citizenshipByNaturalizationRadioButton.setText("by naturalization");
        citizenshipByNaturalizationRadioButton.setEnabled(false);
        citizenshipByNaturalizationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipByNaturalizationRadioButtonActionPerformed(evt);
            }
        });

        citizenshipGroup.add(citizenshipByBirthRadioButton);
        citizenshipByBirthRadioButton.setText("by birth");
        citizenshipByBirthRadioButton.setEnabled(false);
        citizenshipByBirthRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipByBirthRadioButtonActionPerformed(evt);
            }
        });

        surnameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel3.setText("Country (if dual citizenship)");

        countryTextField.setBackground(new java.awt.Color(250, 250, 250));
        countryTextField.setEnabled(false);
        countryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryTextFieldFocusLost(evt);
            }
        });
        countryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(surnameLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(surnameLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(middleNameLabel)
                                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameExtensionLabel)
                                    .addComponent(nameExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dobLabel1)
                                                .addComponent(dobLabel)
                                                .addComponent(placeOfBirthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                                .addComponent(dateOfBirthTextField))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dobLabel2)
                                                .addComponent(placeOfBirthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(surnameLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(maleButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(femaleButton))
                                            .addComponent(otherButton)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(widowedButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(separateButton))
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(singleButton)
                                                .addGap(36, 36, 36)
                                                .addComponent(marriedButton))))
                                    .addComponent(nameExtensionLabel1)
                                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameExtensionLabel5)
                                    .addComponent(philHealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameExtensionLabel2)
                                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameExtensionLabel3)
                                    .addComponent(gsisIdNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameExtensionLabel4)
                                    .addComponent(pagIbigIdNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameExtensionLabel8)
                                    .addComponent(agencyEmployeeNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameExtensionLabel7)
                                    .addComponent(tinNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameExtensionLabel6)
                                    .addComponent(sssNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(informationLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(citizenshipByBirthRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(citizenshipByNaturalizationRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(filipinoButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(dualCitizenshipButton)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(surnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dobLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(placeOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(dobLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(placeOfBirthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameExtensionLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(firstNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addComponent(middleNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameExtensionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameExtensionLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sssNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameExtensionLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tinNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameExtensionLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agencyEmployeeNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameExtensionLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameExtensionLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gsisIdNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameExtensionLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pagIbigIdNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(surnameLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(maleButton)
                                            .addComponent(femaleButton))
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(singleButton)
                                            .addComponent(marriedButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(widowedButton)
                                            .addComponent(separateButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otherButton)))
                                .addGap(18, 18, 18)
                                .addComponent(nameExtensionLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(philHealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surnameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filipinoButton)
                    .addComponent(dualCitizenshipButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citizenshipByNaturalizationRadioButton)
                    .addComponent(citizenshipByBirthRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surnameLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    private void surnameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameTextFieldFocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_surnameTextFieldFocusGained

    private void surnameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameTextFieldFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_surnameTextFieldFocusLost

    private void placeOfBirthTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placeOfBirthTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthTextFieldFocusGained

    private void placeOfBirthTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placeOfBirthTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthTextFieldFocusLost

    private void placeOfBirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOfBirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthTextFieldActionPerformed

    private void middleNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldFocusGained

    private void middleNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldFocusLost

    private void middleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldActionPerformed

    private void nameExtensionTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameExtensionTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameExtensionTextFieldFocusGained

    private void nameExtensionTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameExtensionTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nameExtensionTextFieldFocusLost

    private void nameExtensionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameExtensionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameExtensionTextFieldActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void singleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singleButtonActionPerformed

    private void marriedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marriedButtonActionPerformed

    private void widowedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widowedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widowedButtonActionPerformed

    private void separateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_separateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_separateButtonActionPerformed

    private void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherButtonActionPerformed

    private void firstNameTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField1FocusGained

    private void firstNameTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField1FocusLost

    private void firstNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField1ActionPerformed

    private void placeOfBirthTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placeOfBirthTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthTextField1FocusGained

    private void placeOfBirthTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placeOfBirthTextField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthTextField1FocusLost

    private void placeOfBirthTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOfBirthTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthTextField1ActionPerformed

    private void weightTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldFocusGained

    private void weightTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldFocusLost

    private void weightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldActionPerformed

    private void bloodTypeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodTypeTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeTextFieldFocusGained

    private void bloodTypeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodTypeTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeTextFieldFocusLost

    private void bloodTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeTextFieldActionPerformed

    private void gsisIdNoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gsisIdNoTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_gsisIdNoTextFieldFocusGained

    private void gsisIdNoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gsisIdNoTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_gsisIdNoTextFieldFocusLost

    private void gsisIdNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsisIdNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsisIdNoTextFieldActionPerformed

    private void pagIbigIdNoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagIbigIdNoTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pagIbigIdNoTextFieldFocusGained

    private void pagIbigIdNoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagIbigIdNoTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pagIbigIdNoTextFieldFocusLost

    private void pagIbigIdNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagIbigIdNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagIbigIdNoTextFieldActionPerformed

    private void philHealthNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_philHealthNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_philHealthNoFocusGained

    private void philHealthNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_philHealthNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_philHealthNoFocusLost

    private void philHealthNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philHealthNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philHealthNoActionPerformed

    private void sssNoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sssNoTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_sssNoTextFieldFocusGained

    private void sssNoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sssNoTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_sssNoTextFieldFocusLost

    private void sssNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssNoTextFieldActionPerformed

    private void tinNoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinNoTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tinNoTextFieldFocusGained

    private void tinNoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinNoTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tinNoTextFieldFocusLost

    private void tinNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinNoTextFieldActionPerformed

    private void agencyEmployeeNoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agencyEmployeeNoTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_agencyEmployeeNoTextFieldFocusGained

    private void agencyEmployeeNoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agencyEmployeeNoTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_agencyEmployeeNoTextFieldFocusLost

    private void agencyEmployeeNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agencyEmployeeNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agencyEmployeeNoTextFieldActionPerformed

    private void filipinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filipinoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filipinoButtonActionPerformed

    private void dualCitizenshipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dualCitizenshipButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dualCitizenshipButtonActionPerformed

    private void dualCitizenshipButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dualCitizenshipButtonItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            citizenshipByBirthRadioButton.setEnabled(true);
            citizenshipByNaturalizationRadioButton.setEnabled(true);
            countryTextField.setEnabled(true);
        } else {
            citizenshipByBirthRadioButton.setEnabled(false);
            citizenshipByNaturalizationRadioButton.setEnabled(false);
            countryTextField.setEnabled(false);
            citizenshipButtonGroup.clearSelection(); // Clear the selection
            countryTextField.setText("");
        }
    }//GEN-LAST:event_dualCitizenshipButtonItemStateChanged

    private void citizenshipByNaturalizationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipByNaturalizationRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citizenshipByNaturalizationRadioButtonActionPerformed

    private void citizenshipByBirthRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipByBirthRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citizenshipByBirthRadioButtonActionPerformed

    private void countryTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldFocusGained

    private void countryTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldFocusLost

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agencyEmployeeNoTextField;
    private javax.swing.JTextField bloodTypeTextField;
    private javax.swing.ButtonGroup citizenshipButtonGroup;
    private javax.swing.JRadioButton citizenshipByBirthRadioButton;
    private javax.swing.JRadioButton citizenshipByNaturalizationRadioButton;
    private javax.swing.ButtonGroup citizenshipGroup;
    private javax.swing.ButtonGroup civilStatusButtonGroup;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JFormattedTextField dateOfBirthTextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel dobLabel1;
    private javax.swing.JLabel dobLabel2;
    private javax.swing.JRadioButton dualCitizenshipButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JRadioButton filipinoButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField1;
    private javax.swing.JTextField gsisIdNoTextField;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JRadioButton marriedButton;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JLabel nameExtensionLabel;
    private javax.swing.JLabel nameExtensionLabel1;
    private javax.swing.JLabel nameExtensionLabel2;
    private javax.swing.JLabel nameExtensionLabel3;
    private javax.swing.JLabel nameExtensionLabel4;
    private javax.swing.JLabel nameExtensionLabel5;
    private javax.swing.JLabel nameExtensionLabel6;
    private javax.swing.JLabel nameExtensionLabel7;
    private javax.swing.JLabel nameExtensionLabel8;
    private javax.swing.JTextField nameExtensionTextField;
    private javax.swing.JRadioButton otherButton;
    private javax.swing.JTextField pagIbigIdNoTextField;
    private javax.swing.JTextField philHealthNo;
    private javax.swing.JTextField placeOfBirthTextField;
    private javax.swing.JTextField placeOfBirthTextField1;
    private javax.swing.JRadioButton separateButton;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.JRadioButton singleButton;
    private javax.swing.JTextField sssNoTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel surnameLabel1;
    private javax.swing.JLabel surnameLabel2;
    private javax.swing.JLabel surnameLabel3;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JTextField tinNoTextField;
    private javax.swing.JTextField weightTextField;
    private javax.swing.JRadioButton widowedButton;
    // End of variables declaration//GEN-END:variables
}
